[tool.poetry]
name = "telegram-bot"
version = "0.1.0"
description = "Telegram bot project"
authors = ["Your Name <you@example.com>"]
python = "^3.10"

[tool.poetry.dependencies]
python = "^3.10"
python-telegram-bot = "20.7"
nest_asyncio = "1.5.7"
openpyxl = "3.1.2"
requests = "2.31.0"
python-dotenv = "1.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
